#!/usr/bin/env python3
"""
patch_llms_link.py — make /llms.txt discoverable from every authored page.

/llms.txt returns 200 and is well written, but nothing links to it: zero pages,
zero sitemap entries (handoff 2026-07-17 §3.2). It is reachable only by a
client that already knows the convention and tries the URL blind. This patcher
closes the page half of that gap: one <link rel="alternate"> in the head of
every authored surface, anchored on the canonical tag. The sitemap half lives
in build_site_meta.py, which now emits /llms.txt as a ledger-derived URL.

TARGETS: the four static pages plus every built landing — authored surfaces
only. Read pages are regenerated from docx and would silently drop an injected
line on rebuild (patch_kernel_terms doctrine); they inherit the same line from
tools/uct-paper.html, which this change also carries, at their next natural
rebuild. Non-slug-conditional content in the global template is the right
shape; injecting into generated files is not.

CONTENT: this tool does not touch llms.txt itself. That file is generated by
build_llms and already complete (§6: a partial read is not a read).

Idempotent by construction: any existing llms alternate line is removed and
one fresh line inserted after the canonical tag, so a second run produces zero
bytes of diff. Fail-loud: refuses any page whose canonical anchor is not
exactly-once, and refuses to run at all if public/llms.txt is absent on disk.

Repeatable; dry-run by default; --apply writes. No backups: git is the backup.

    python3 tools/patch_llms_link.py
    python3 tools/patch_llms_link.py --apply
"""
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("needs pyyaml")

DATA = "tools/site_data.yaml"
PUB = Path("public")

RE_CANON = re.compile(r'^([ \t]*)<link rel="canonical"[^\n]*\n', re.M)
RE_OLD = re.compile(r'^[ \t]*<link rel="alternate"[^\n]*llms\.txt[^\n]*\n', re.M)


def loc_to_file(loc):
    """'/' -> index.html, '/library' -> library.html, '/roadmap/' -> roadmap/index.html"""
    if loc == "/":
        return "index.html"
    if loc.endswith("/"):
        return loc.strip("/") + "/index.html"
    return loc.strip("/") + ".html"


def main():
    apply = "--apply" in sys.argv
    d = yaml.safe_load(open(DATA))
    base = d["site"]["base"].rstrip("/")
    line = (f'<link rel="alternate" type="text/plain" href="{base}/llms.txt" '
            f'title="llms.txt — corpus index for AI agents">')

    if not (PUB / "llms.txt").exists():
        sys.exit("FAIL  public/llms.txt does not exist — refusing to link 45 "
                 "pages at a 404; run build_site_meta.py first")

    targets = [loc_to_file(p["loc"]) for p in d.get("pages", [])]
    targets += [f"{p['slug']}.html" for p in d.get("papers", []) if p.get("built")]

    changed, unchanged = [], []
    for rel in targets:
        f = PUB / rel
        if not f.exists():
            sys.exit(f"FAIL  {rel}: target page missing")
        s = f.read_text(encoding="utf-8")

        canons = RE_CANON.findall(s)
        if len(canons) != 1:
            sys.exit(f"FAIL  {rel}: canonical anchor count {len(canons)}, "
                     f"need exactly 1 — refusing to guess")

        t = RE_OLD.sub("", s)
        m = RE_CANON.search(t)
        indent = m.group(1)
        t = t[: m.end()] + f"{indent}{line}\n" + t[m.end():]

        if t == s:
            unchanged.append(rel)
        else:
            changed.append(rel)
            if apply:
                f.write_text(t, encoding="utf-8")

    mode = "APPLIED" if apply else "DRY-RUN (use --apply)"
    print(f"{mode}: {len(changed)} page(s) changed, {len(unchanged)} already correct, "
          f"{len(targets)} targeted")

    if apply:
        # verification on written bytes: exact line, exactly once, every target
        bad = 0
        for rel in targets:
            n = (PUB / rel).read_text(encoding="utf-8").count(line)
            if n != 1:
                print(f"VERIFY FAIL  {rel}: llms link count {n}, want 1")
                bad += 1
        if bad:
            sys.exit(f"{bad} page(s) failed post-write verification")
        print(f"verified: llms.txt alternate link exactly once on all {len(targets)} pages")


if __name__ == "__main__":
    main()
